name: Validate Branch Rules

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - next
permissions:
  contents: read

jobs:
  validate_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name and target
        run: |
          source_branch="${{ github.head_ref }}"
          target_branch="${{ github.base_ref }}"
          
          # Allow certain system/integration branches to bypass naming convention
          if [[ "$source_branch" =~ ^(main|next|develop|master)$ ]]; then
            echo "System branch '$source_branch' is exempt from naming convention."
          else
            # Check if the source branch name is valid (feature/bugfix/hotfix)
            if ! [[ "$source_branch" =~ ^(feature|bugfix|hotfix)/.+$ ]]; then
              echo "::error::Branch name '$source_branch' does not follow the naming convention (feature/, bugfix/, hotfix/)."
              exit 1
            fi
          fi
          
          # Check if a feature or bugfix branch is targeting the correct branch (next)
          if [[ "$source_branch" =~ ^(feature|bugfix)/.+ ]] && [ "$target_branch" != "next" ]; then
            echo "::error::'feature/*' and 'bugfix/*' branches must only be merged into 'next'."
            exit 1
          fi

          # Check if a hotfix branch is targeting the correct branch (main)
          if [[ "$source_branch" =~ ^hotfix/.+ ]] && [ "$target_branch" != "main" ]; then
            echo "::error::'hotfix/*' branches must only be merged into 'main'."
            exit 1
          fi
          
          echo "Branch rules validated successfully."